# Generated by Django 4.0.1 on 2022-01-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image_post_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likecount',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='like_count'),
        ),
    ]
